#!/bin/bash

function create {
insmod dm-cache.ko
echo 0 6291456 cache /dev/dm-cache/lv-node1-disk  /dev/sda6 0 8 131072 1024 0 | dmsetup create cache1
echo 0 6291456 cache /dev/dm-cache/lv-node2-disk  /dev/sda6 0 8 131072 1024 0 | dmsetup create cache2
}

function create2 {
insmod dm-cache.ko
echo 0 6291456 cache /dev/dm-cache/lv-node2-disk  /dev/sda6 0 1 131072 1 0 | dmsetup create cache2
}

function linear {
insmod dm-linear.ko
echo 0 6291456 linear /dev/dm-cache/lv-node2-disk 0 | dmsetup create cache2
}


function mounting {
mount /dev/mapper/cache1 /mnt/cache1
mount /dev/mapper/cache2 /mnt/cache2
mount
}
function start_cache {
	create
	mounting
}
function destroy {
	umount /mnt/cache1
	umount /mnt/cache2

	dmsetup remove cache1
	dmsetup remove cache2	
	rmmod dm_cache
	rmmod dm_linear
}

case "$1" in

	start)
		start_cache
		;;
	create)
		create
		;;
	destroy)
		destroy
		;;
	cache2)
		create2
		;;
	linear)
		linear
		;;
	*)
		echo "$0 create/destroy"
		;;
esac
