#!/bin/sh
. configure.paths

install -m 755 cachetest $CONFIG_BINPATH/cachetest

if [ `whoami` = "root" ]; then
  etcpath=/etc
else
  if [ -d "${HOME}/.etc" ]; then
    etcpath="${HOME}/.etc"
  else
    mkdir -p "${HOME}/etc"
    etcpath="${HOME}/etc"
  fi
  mkdir -p "${HOME}/var/run"
fi

if [ ! -e "${etcpath}/cachetest.conf" ]; then
  cp rsrc/cachetest.conf "$etcpath"/cachetest.conf
fi
